# Environment
language: cpp
compiler:
#  - gcc
  - clang

# Install build dependencies
before_script:
  - sudo apt-get install npm protobuf-compiler protobuf-c-compiler libprotobuf-dev libv8-dev libgoogle-perftools-dev libprotoc-dev default-jre python-yaml time python-protobuf python-pylibmc
  - sudo npm install -g less@1.3.0
  - sudo npm install -g coffee-script@1.4.0
  - sudo npm install -g handlebars@1.0.10
  - sudo npm install -g mocha
  - gem install ruby_protobuf

  # we need a custom ppa for latest boost libs (1.46, which is on
  # Travis, doesn't work with Clang and C++ 11)
  - yes | sudo apt-add-repository ppa:jkeiren/ppa
  - sudo apt-get update
  - sudo apt-get install libboost1.48-all-dev

# Build script
script:
  - ./configure
  - make -j 3 test-deps
  - make -C test/rql_test js_polyglot TEST=regression-767
#  - make test TEST=travis RUN_TEST_ARGS='-j3 -w-'

# Notify only on change
notifications:
  email:
    on_success: change
    on_failure: change
