# Environment
language: cpp
compiler:
  - gcc
  - clang

# Install build dependencies
before_script:
  - sudo apt-get install npm protobuf-compiler protobuf-c-compiler libprotobuf-dev libv8-dev libgoogle-perftools-dev libprotoc-dev default-jre libboost-all-dev
  - sudo npm install -g less@1.3.0
  - sudo npm install -g coffee-script@1.4.0
  - sudo npm install -g handlebars@1.0.10

# Build script
script: ./configure && make DEBUG=1 unit -j 2

# Notify only on change
notifications:
  email:
    on_success: change
    on_failure: change
